CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`description` text NOT NULL,
	`descriptionEn` text,
	`category` varchar(100) NOT NULL,
	`subcategory` varchar(100),
	`price` int NOT NULL,
	`servingSize` varchar(100),
	`image` text NOT NULL,
	`imageAlt` varchar(255),
	`isVegetarian` boolean NOT NULL DEFAULT false,
	`isVegan` boolean NOT NULL DEFAULT false,
	`isGlutenFree` boolean NOT NULL DEFAULT false,
	`isDairyFree` boolean NOT NULL DEFAULT false,
	`calories` int,
	`protein` int,
	`carbs` int,
	`fat` int,
	`nutritionalTip` text,
	`nutritionalTipEn` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`displayOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
