/**
 * Image generation helper using OpenAI DALL-E
 *
 * Example usage:
 *   const { url: imageUrl } = await generateImage({
 *     prompt: "A serene landscape with mountains"
 *   });
 */

export type GenerateImageOptions = {
  prompt: string;
  originalImages?: Array<{
    url?: string;
    b64Json?: string;
    mimeType?: string;
  }>;
};

export type GenerateImageResponse = {
  url?: string;
  revisedPrompt?: string;
};

export async function generateImage(
  options: GenerateImageOptions
): Promise<GenerateImageResponse> {
  const openaiApiKey = process.env.OPENAI_API_KEY;
  
  if (!openaiApiKey) {
    throw new Error("OPENAI_API_KEY is not configured. Please add it to your environment variables.");
  }

  // DALL-E 3 doesn't support image editing, only generation
  if (options.originalImages && options.originalImages.length > 0) {
    console.warn("Image editing is not supported with DALL-E 3. Generating new image instead.");
  }

  try {
    // Call OpenAI DALL-E API
    const response = await fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${openaiApiKey}`,
      },
      body: JSON.stringify({
        model: "dall-e-3",
        prompt: options.prompt,
        n: 1,
        size: "1024x1024",
        quality: "standard",
        response_format: "url",
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage = (errorData as any)?.error?.message || response.statusText;
      throw new Error(`OpenAI API error: ${errorMessage}`);
    }

    const result = await response.json() as {
      data: Array<{
        url: string;
        revised_prompt?: string;
      }>;
    };

    if (!result.data || result.data.length === 0) {
      throw new Error("No image generated by OpenAI");
    }

    // Return OpenAI URL directly (valid for 1 hour)
    // For permanent storage, you would need to download and re-upload to your own storage
    return {
      url: result.data[0].url,
      revisedPrompt: result.data[0].revised_prompt,
    };
  } catch (error: any) {
    console.error("Image generation error:", error);
    
    // Provide user-friendly error messages
    if (error?.message?.includes("content_policy")) {
      throw new Error("The image could not be generated due to content policy restrictions. Please modify your prompt.");
    }
    if (error?.message?.includes("billing") || error?.message?.includes("quota")) {
      throw new Error("OpenAI API quota exceeded. Please check your billing settings.");
    }
    if (error?.message?.includes("invalid_api_key")) {
      throw new Error("Invalid OpenAI API key. Please check your configuration.");
    }
    
    throw error;
  }
}
