/**
 * Image generation helper using OpenAI DALL-E
 *
 * Example usage:
 *   const { url: imageUrl } = await generateImage({
 *     prompt: "A serene landscape with mountains"
 *   });
 *
 * Note: Image editing is not supported with DALL-E 3
 * For editing, consider using DALL-E 2 or other services
 */
import { storagePut } from "server/storage";

export type GenerateImageOptions = {
  prompt: string;
  originalImages?: Array<{
    url?: string;
    b64Json?: string;
    mimeType?: string;
  }>;
};

export type GenerateImageResponse = {
  url?: string;
};

export async function generateImage(
  options: GenerateImageOptions
): Promise<GenerateImageResponse> {
  const openaiApiKey = process.env.OPENAI_API_KEY;
  
  if (!openaiApiKey) {
    throw new Error("OPENAI_API_KEY is not configured. Please add it to your .env file.");
  }

  // DALL-E 3 doesn't support image editing, only generation
  if (options.originalImages && options.originalImages.length > 0) {
    console.warn("Image editing is not supported with DALL-E 3. Generating new image instead.");
  }

  try {
    // Call OpenAI DALL-E API
    const response = await fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${openaiApiKey}`,
      },
      body: JSON.stringify({
        model: "dall-e-3",
        prompt: options.prompt,
        n: 1,
        size: "1024x1024",
        quality: "standard",
        response_format: "url", // Get URL directly from OpenAI
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `OpenAI API request failed (${response.status} ${response.statusText}): ${JSON.stringify(errorData)}`
      );
    }

    const result = await response.json() as {
      data: Array<{
        url: string;
        revised_prompt?: string;
      }>;
    };

    if (!result.data || result.data.length === 0) {
      throw new Error("No image generated by OpenAI");
    }

    const imageUrl = result.data[0].url;

    // Download the image from OpenAI
    const imageResponse = await fetch(imageUrl);
    if (!imageResponse.ok) {
      throw new Error(`Failed to download generated image: ${imageResponse.statusText}`);
    }

    const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());

    // Save to S3 storage
    const { url } = await storagePut(
      `generated/${Date.now()}.png`,
      imageBuffer,
      "image/png"
    );

    return { url };
  } catch (error) {
    console.error("Image generation error:", error);
    throw error;
  }
}
